### ISSUE TITLE
Doesn't seem to work currently

### ISSUE THREAD

**Issue by halfrubbish** [homespun/homebridge-accessory-neurio#1]
The Home ios app reports "The accessory is not currently supported by the Home app", and does not display any power usage.

It can however see at the bottom of the screen "Manufacturer neur.io, Serial number <IPAddress>, Model: Home Energy Monitor"

**Comment by mrose17** [comment]
thanks for the report. Apple's iOS app is a bit "thin" when it comes to the devices that it supports.

i have tried every homekit app for iOS ever written (seriously!) so  my fave is https://www.elgato.com/en/eve/eve-app  (if you have a different favorite app, let me know so i can see if i can try it.)

anyway, here's what it looks like on eve:

![img_0292](https://cloud.githubusercontent.com/assets/400552/19091819/fd5fc46a-8a38-11e6-8d43-0d8f872e0979.jpg)

/mtr

ps: sorry for the delay in replying, for some reason i don't see these messages via github. just put a @mrose17 in your reply and i'll see it. thanks!

**Comment by halfrubbish** [comment]
Thanks for your reply @mrose17 ! 

I installed that app and it seems to work well now. It was quite strange because I was doing a CURL -X directly against the homebridge to pull back some JSON which included all values and paremeters, but for this neurio app it only pulled back 0 for all values _until_ I started using the elgato app. It seems this json state is based on a cache of the last time an actual homekit device queried homebridge.

Have you seen this kind of behaviour before? I'm basically trying to write a website that displays the current state of all sensors superimposed on a floor plan, based on this json file, but perhaps I should be talking native homekit instead to actually get the values. Unfortunately the only documented  reverse engineered API of that was DMCA'd by Apple. Don't suppose you know of any other useful ways of doing this?

Thanks!

**Comment by mrose17** [comment]
interesting. sadly, no, i don't know of any API that's available. i suspect that you may have to write an iOS app (or perhaps a macOS app sometime in the future) that fetches and stores in a place where your website can get at it... sorry!
