### ISSUE TITLE
Update not working?

### ISSUE THREAD

**Issue by mbierman** [homespun/homebridge-accessory-neurio#11]
I’m probably doing something wrong, but when I run

`npm update homebridge-accessory-neurio`

Nothing happens. 

Have I done something wrong?

**Comment by mrose17** [comment]
did you perhaps mean to use `npm update -g homebridge-accessory-neurio` ?

**Comment by mbierman** [comment]
In homebridge UI plugins don’t get installed globally.

**Comment by mrose17** [comment]
OK, since i'm not a homebridge UI user, i can't really comment on a solution... sorry!

when you say "nothing happens." what output is there when you type the command?

**Comment by mbierman** [comment]
Nada. No output at all.

**Comment by mrose17** [comment]
i see exactly the same nothing. OK, try `npm install homebridge-accessory-neurio` ... that seems to work...

**Comment by mbierman** [comment]
O.K. i have a script to run It nightly so “update” might have been nice, but I guess it doesn’t matter.

**Comment by mrose17** [comment]
sorry, i don't know why "npm update" stopped working for both of us...
