### ISSUE TITLE
Fails to connect to neutrino

### ISSUE THREAD

**Issue by stuwilkins** [homespun/homebridge-accessory-neurio#2]
I have just installed the neurio. In trying to get this to work, I get errors from the plugin:

```
<<< GET http://192.168.1.7/current-sample
<<<
[ response for GET http://192.168.1.7/current-sample ]
>>> HTTP/1.1 301
>>> location: /
>>> content-type: text/html
>>> connection: Keep-Alive
>>>
>>>
[12/24/2016, 5:30:58 PM] [Home Energy Monitor] _roundTrip error: HTTP response 301
[12/24/2016, 5:30:58 PM] [Home Energy Monitor] roundTrip error: Error: HTTP response 301
```
It appears that perhaps the API changed. In trying this on the command line, I get:

```
[swilkins@Stuarts-MacBook ~]$ curl -i -X GET    -H "Content-Type:application/json" 'http://192.168.1.7/current-sample'
HTTP/1.1 301
Location: /
Content-Type: text/html
Connection: Keep-Alive
```

Anyone run into this? Thanks!

**Comment by mrose17** [comment]
that's rather odd: here's what i get from my neur.io:

        {
          "sensorId": "0x0000......",
          "timestamp": "2016-12-29T00:41:47Z",
          "channels": [
            {
              "type": "PHASE_A_CONSUMPTION",
              "ch": 1,
              "eImp_Ws": 43067911317,
              "eExp_Ws": 95257,
              "p_W": 275,
              "q_VAR": -90,
              "v_V": 123.271
            },
            {
              "type": "PHASE_B_CONSUMPTION",
              "ch": 2,
              "eImp_Ws": 55723553139,
              "eExp_Ws": 244709,
              "p_W": 278,
              "q_VAR": -14,
              "v_V": 123.321
            },
            {
              "type": "CONSUMPTION",
              "ch": 3,
              "eImp_Ws": 98791464530,
              "eExp_Ws": 339972,
              "p_W": 553,
              "q_VAR": -104,
              "v_V": 123.296
            }
          ],
          "cts": [
            {
              "ct": 1,
              "p_W": 275,
              "q_VAR": -90,
              "v_V": 123.271
            },
            {
              "ct": 2,
              "p_W": 278,
              "q_VAR": -14,
              "v_V": 123.321
            },
            {
              "ct": 3,
              "p_W": 0,
              "q_VAR": 0,
              "v_V": 0
            },
            {
              "ct": 4,
              "p_W": 0,
              "q_VAR": 0,
              "v_V": 123.269
            }
          ]
        }

if you point hour browser at http://192.168.1.7/ what comes back?

thanks!

**Comment by stuwilkins** [comment]
Hi, 

Happy new year!

Sorry ... this was caused by the outage over the new year. All back and running now! 

Thanks.
S
