### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by helo-head** [homespun/homebridge-accessory-neurio#5]
Ran into a strange problem for which the symptoms changed between NPM 5.6 and 6.2. In either case I could not install using **sudo npm install -g --unsafe-perm homebridge-accessory-neurio**. Im looking for ideas on how to isolate 

**Under NPM 5.6 I got the following**
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-2a997957
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-2a997957': Permission denied

Thinking this might be an NPM issue I upgraded to NPM 6.2 

**Under NPM 6.2 - I get the following**
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-e75c7bfb': Permission denied

**Comment by mrose17** [comment]
hi. sorry for the delay in replying. try a fresh install of the package, it's been udpated to use the latest pcap library, and that should fix the issue!

thanks to @mkormendy for the fix!
