### ISSUE TITLE
Screenshot 

### ISSUE THREAD

**Issue by lfiocco** [homespun/homebridge-accessory-neurio#6]
Hello can someone please post a screenshot of what this looks like through the home app?

**Comment by mrose17** [comment]
sorry for the delay in replying. the iOS home app says:
![IMG_0343](https://user-images.githubusercontent.com/400552/65632661-1197f700-df8f-11e9-8ef0-29763dc3c3dd.png)
however, if you use a "better" app like elgato eve, you will see:
![IMG_0342](https://user-images.githubusercontent.com/400552/65632682-207ea980-df8f-11e9-87be-4aa36b96728a.png)
