### ISSUE TITLE
Security issue Support Neurio basic auth

### ISSUE THREAD

**Issue by mbierman** [homespun/homebridge-accessory-neurio#7]
Because basic auth isn’t supported, users have to chose between securing their neurio and using this plugin. It would be wonderful of this plugin supported neurio basic auth.

**Comment by mrose17** [comment]
thanks for the report. try `homebridge-accessory-neurio@0.9.9` and see if that works for you...

**Comment by mbierman** [comment]
Seems to work for me. Thank you so much.

**Comment by mrose17** [comment]
Great, enjoy!
