### ISSUE TITLE
homebridge-accessory-neurio missing from homebridge portal

### ISSUE THREAD

**Issue by mbierman** [homespun/homebridge-accessory-neurio#8]
I am no longer seeing the plugin in the homebridge portal but I do see it in Eve and the Home app. I want to say that in the previous version I saw it in the portal but I could be wrong about that.

**Comment by Paul7200** [comment]
Just installed, same issue. Shows as "unsupported" in the home app, but all data accessible via Eve.

**Comment by mrose17** [comment]
it is in the home app, it's just "unsupported". fortunately the Eve app doesn't "just punt" but shows what it can!
