### ISSUE TITLE
Round trip error

### ISSUE THREAD

**Issue by mbierman** [homespun/homebridge-accessory-neurio#9]
I’m seeing an error for the plugin. I thought it might be auth related  (like an invalid token) so i changed the password and the problem went away but only briefly. 

Any ideas how to resolve this?

![8488DEFC-20D9-48E3-ACFE-9EA5A3B2FEC5](https://user-images.githubusercontent.com/1205471/81140190-591b3400-8f1d-11ea-82e2-fbe3f1f5b3de.jpeg)

**Comment by mrose17** [comment]
sorry for the delay in replying, for some reason, github issues are email-reported intermittently to me.

is this still happening? a good explanation of  ECONNRESET is from https://stackoverflow.com/questions/17245881/how-do-i-debug-error-econnreset-in-node-js -- there is a lot of text there, but the significant comment is:

        What could also be the case: at random times, the other side is overloaded and simply kills
        the connection as a result. If that's the case, depends on what you're connecting to exactly…

i have been running the plugin for several months and while occasionally there's a connectivity error preventing a connection from being established, i haven't seen an ECONNRESET...
